export const uiStrings = {
  en: {
    // Header
    siteTitle: "Thirukkural: The Eternal Wisdom",
    headerTitle: "Thirukkural",
    searchPlaceholder: "Search by Kural #, chapter, or keyword...",
    home: "Home",
    
    // Navigation
    navigation: "Navigation",
    myFavorites: "My Favorites",
    fullThirukkural: "Full Thirukkural",
    sections: "sections",
    chapters: "chapters",

    // Kural List
    searchResultsFor: "Search Results for",
    searchResultsTitle: "Search Results",
    noResultsFound: "No results found. Please try a different search term.",

    // Favorites Page
    noFavoritesTitle: "No Favorites Yet",
    noFavoritesDescription: "Tap the heart icon on any Kural to save it here for quick access.",

    // Kural Of The Day
    kuralOfTheDay: "Kural of the Day",
    viewDetails: "View Details",

    // Kural Detail View
    kural: "Kural",
    english: "English",
    hindi: "Hindi",
    tamil: "Tamil",
    translations: "Translations",
    commentaries: "Commentaries",
    noCommentaries: "No commentaries are available for this Kural at this time.",
    tamilCommentary: "Tamil Commentary",
    copiedToClipboard: "Kural copied to clipboard!",
    listen: "Listen to pronunciation",
    audioInfo: "Audio pronunciation requires a Tamil (ta-IN) voice pack to be installed on your operating system for the best experience.",

    // About Section Table
    aboutTableTitle: "Structure of the Thirukkural",
    colSection: "Section (Paal)",
    colTamilName: "Tamil Name",
    colChapters: "No. of Chapters",
    colKurals: "No. of Kurals",
    total: "Total",

    // About Thiruvalluvar
    aboutThiruvalluvarTitle: "About Thiruvalluvar",
    thiruvalluvarP1: "Thiruvalluvar was a celebrated Tamil poet and philosopher whose contribution to Tamil literature is the Thirukkural, a work on ethics, politics, economics, and love. The exact time of his life is debated, with scholars placing him anywhere from the 4th century BCE to the 5th century CE.",
    thiruvalluvarP2: "Referred to with veneration as Valluvar, he is celebrated for his secular and universal teachings, which transcend religious, cultural, and temporal boundaries. His work remains a beacon of wisdom, guiding humanity towards an ethical and harmonious life.",

    // Settings Panel
    settings: "Settings",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    sepia: "Sepia",
    fontSize: "Font Size",

    // All Kurals View
    jumpToChapter: "Jump to Chapter...",

    // FIX: Added missing UI strings for the Themes page.
    // Themes Page
    themesPageTitle: "Themes",
    themesPageDescription: "Explore Kurals grouped by common themes generated by AI. View any Kural to analyze and add its themes here.",
    noThemesGenerated: "No themes have been generated yet. View a Kural to generate its themes.",

    // Quiz
    quiz: "Quiz",
    quizTitle: "Aram Quiz",
    question: "Question",
    of: "of",
    whichKural: "What is the English translation for this Kural?",
    quizResults: "Quiz Results",
    yourScore: "Your Score",
    playAgain: "Play Again",
    correct: "Correct!",
    wrong: "Wrong!",
    victoryMessage: "Well done! You have a great understanding of Thirukkural.",
  },
  ta: {
    // Header
    siteTitle: "திருக்குறள்: நித்திய ஞானம்",
    headerTitle: "திருக்குறள்",
    searchPlaceholder: "குறள் எண், அதிகாரம், அல்லது முக்கிய வார்த்தை மூலம் தேடவும்...",
    home: "முகப்பு",
    
    // Navigation
    navigation: "வழிசெலுத்தல்",
    myFavorites: "எனக்குப் பிடித்தவை",
    fullThirukkural: "முழு திருக்குறள்",
    sections: "இயல்கள்",
    chapters: "அதிகாரங்கள்",

    // Kural List
    searchResultsFor: "தேடல் முடிவுகள்",
    searchResultsTitle: "தேடல் முடிவுகள்",
    noResultsFound: "முடிவுகள் எதுவும் கிடைக்கவில்லை. வேறு தேடல் வார்த்தையை முயற்சிக்கவும்.",

    // Favorites Page
    noFavoritesTitle: "பிடித்தவை எதுவும் இல்லை",
    noFavoritesDescription: "விரைவான அணுகலுக்கு, எந்தவொரு குறளிலும் உள்ள இதய ஐகானைத் தட்டி இங்கே சேமிக்கவும்.",
    
    // Kural Of The Day
    kuralOfTheDay: "இன்றைய குறள்",
    viewDetails: "விவரங்களைக் காண்க",

    // Kural Detail View
    kural: "குறள்",
    english: "ஆங்கிலம்",
    hindi: "இந்தி",
    tamil: "தமிழ்",
    translations: "மொழிபெயர்ப்புகள்",
    commentaries: "உரைகள்",
    noCommentaries: "இந்தக் குறளுக்கு தற்போது உரைகள் எதுவும் கிடைக்கவில்லை.",
    tamilCommentary: "தமிழ் விளக்கம்",
    copiedToClipboard: "குறள் நகலெடுக்கப்பட்டது!",
    listen: "உச்சரிப்பைக் கேளுங்கள்",
    audioInfo: "சிறந்த அனுபவத்திற்கு, உங்கள் இயக்க முறைமையில் தமிழ் (ta-IN) குரல் தொகுப்பு நிறுவப்பட்டிருக்க வேண்டும்.",

    // About Section Table
    aboutTableTitle: "திருக்குறள் அமைப்பு",
    colSection: "பால்",
    colTamilName: "தமிழ் பெயர்",
    colChapters: "அதிகாரங்கள்",
    colKurals: "குறள்கள்",
    total: "மொத்தம்",

    // About Thiruvalluvar
    aboutThiruvalluvarTitle: "திருவள்ளுவர் பற்றி",
    thiruvalluvarP1: "திருவள்ளுவர் ஒரு போற்றப்படும் தமிழ் கவிஞரும் தத்துவஞானியுமாவார், தமிழ் இலக்கியத்திற்கு அவர் ஆற்றிய பங்களிப்பு திருக்குறள் ஆகும். இது அறம், அரசியல், பொருளாதாரம் மற்றும் காதல் பற்றிய ஒரு படைப்பாகும். அவர் வாழ்ந்த சரியான காலம் விவாதத்திற்குரியது, அறிஞர்கள் அவரை கி.மு. 4 ஆம் நூற்றாண்டு முதல் கி.பி. 5 ஆம் நூற்றாண்டு வரை எங்கும் வைக்கின்றனர்.",
    thiruvalluvarP2: "வள்ளுவர் என்று மரியாதையுடன் குறிப்பிடப்படும் இவர், மதம், கலாச்சாரம் மற்றும் கால எல்லைகளைக் கடந்த தனது மதச்சார்பற்ற மற்றும் உலகளாவிய போதனைகளுக்காகக் கொண்டாடப்படுகிறார். அவரது படைப்பு ஞானத்தின் கலங்கரை விளக்கமாகத் திகழ்கிறது, மனிதகுலத்தை ஒரு நெறிமுறை மற்றும் இணக்கமான வாழ்க்கையை நோக்கி வழிநடத்துகிறது.",


    // Settings Panel
    settings: "அமைப்புகள்",
    theme: "கரு",
    light: "ஒளி",
    dark: "இருள்",
    sepia: "செபியா",
    fontSize: "எழுத்துரு அளவு",

    // All Kurals View
    jumpToChapter: "அதிகாரத்திற்குச் செல்ல...",

    // FIX: Added missing UI strings for the Themes page.
    // Themes Page
    themesPageTitle: "கருப்பொருள்கள்",
    themesPageDescription: "AI மூலம் உருவாக்கப்பட்ட பொதுவான கருப்பொருள்களின்படி குழுவாக உள்ள குறள்களை ஆராயுங்கள். எந்தவொரு குறளையும் பார்த்து அதன் கருப்பொருள்களை இங்கே சேர்க்கவும்.",
    noThemesGenerated: "இன்னும் கருப்பொருள்கள் எதுவும் உருவாக்கப்படவில்லை. அதன் கருப்பொருள்களை உருவாக்க ஒரு குறளைப் பார்க்கவும்.",

    // Quiz
    quiz: "வினாடி வினா",
    quizTitle: "அறத்துப்பால் வினாடி வினா",
    question: "கேள்வி",
    of: "/",
    whichKural: "இந்த குறளின் ஆங்கில மொழிபெயர்ப்பு என்ன?",
    quizResults: "வினாடி வினா முடிவுகள்",
    yourScore: "உங்கள் மதிப்பெண்",
    playAgain: "மீண்டும் விளையாடு",
    correct: "சரி!",
    wrong: "தவறு!",
    victoryMessage: "நன்றாக செய்தீர்கள்! உங்களுக்கு திருக்குறள் பற்றிய சிறந்த புரிதல் உள்ளது.",
  }
};